version: '3'
services:
 
  kafka1:
    image: frankv72/bp2024:1.2
    
    ports:
       - 9095:9095
    networks:
       - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==1
    command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties --override broker.id=1 --override num.network.threads=3 --override num.io.threads=8 --override process.roles=broker,controller  --override listeners=BROKER://:9094,CONTROLLER://:9095  --override advertised.listeners=BROKER://:9094 --override listener.security.protocol.map=BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT --override controller.listener.names=CONTROLLER --override controller.quorum.voters=1@:9095 --override inter.broker.listener.name=BROKER --override sasl.enabled.mechanisms=PLAIN --override sasl.mechanism.controller.protocol=PLAIN --override sasl.mechanism.inter.broker.protocol=PLAIN --override authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer --override allow.everyone.if.no.acl.found=false --override super.users=User:admin --override delete.topic.enable=true --override socket.send.buffer.bytes=1048576 --override socket.receive.buffer.bytes=1048576 --override socket.request.max.bytes=104857600 --override num.partitions=3 --override default.replication.factor=2 --override min.insync.replicas=2 --override log.retention.hours=168 --override log.segment.bytes=1073741824 --override log.retention.check.interval.ms=300000 --override auto.create.topics.enable=true --override unclean.leader.election.enable=false
  kafka2:
    image: frankv72/bp2024:1.2
    ports:
       - 9096:9096
    networks:
       - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==2
    command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties --override broker.id=2 --override num.network.threads=3 --override num.io.threads=8 --override process.roles=broker,controller  --override listeners=BROKER://:9094,CONTROLLER://node2:9096 --override advertised.listeners=BROKER://:9094 --override listener.security.protocol.map=BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT --override controller.listener.names=CONTROLLER --override controller.quorum.voters=1@:9095 --override inter.broker.listener.name=BROKER --override sasl.enabled.mechanisms=PLAIN --override sasl.mechanism.controller.protocol=PLAIN --override sasl.mechanism.inter.broker.protocol=PLAIN --override authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer --override allow.everyone.if.no.acl.found=false --override super.users=User:admin --override delete.topic.enable=true --override socket.send.buffer.bytes=1048576 --override socket.receive.buffer.bytes=1048576 --override socket.request.max.bytes=104857600 --override num.partitions=3 --override default.replication.factor=2 --override min.insync.replicas=2 --override log.retention.hours=168 --override log.segment.bytes=1073741824 --override log.retention.check.interval.ms=300000 --override auto.create.topics.enable=true --override unclean.leader.election.enable=false

networks:
  kafka-net:
