version: '3.8'

services:
  spark-yarn-master:
   # build:
    #  dockerfile: Dockerfile
    #  context: '.'
    container_name: da-spark-yarn-master
    image: frankv72/spark-yarn-image:1.0
    hostname: spark-yarn-master
    entrypoint: ['./entrypoint.sh', 'master']
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
    env_file:
      - .env.spark
    ports:
      - '8080:8080'
      - '9870:9870'
      - '7077:7077'
      - '8088:8088'
      - '8032:8032'
      - '9866:9866'

  spark-yarn-worker1:
    container_name: spark-yarn-worker1
    image: frankv72/spark-yarn-image:1.0
    hostname: spark-yarn-worker1
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps

  spark-yarn-worker2:
    container_name: spark-yarn-worker2
    image: frankv72/spark-yarn-image:1.0
    hostname: spark-yarn-worker2
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps

  spark-yarn-worker3:
    container_name: spark-yarn-worker3
    image: frankv72/spark-yarn-image:1.0
    hostname: spark-yarn-worker3

    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps

  yarn-history-server:
    container_name: spark-yarn-history
    hostname: spark-yarn-history
    image: frankv72/spark-yarn-image:1.0

    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    ports:
      - '18080:18080'
networks:
  default:
    driver: host