version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    networks:
        hadoop-net:
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    networks:
        hadoop-net: 
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      
    env_file:
      - ./hadoop.env  
    
volumes:
  hadoop_namenode:
  hadoop_datanode1:


networks:
  hadoop-net:  