version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    networks:
      - hadoop-net
    ports:
      - 40209:9870
      - 40208:9000
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==1
   
    
    ports:
        - 9864:9864
      
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
     
    env_file:
      - ./hadoop.env

  firefox:
    image: jlesage/firefox
    ports:
      - 40210:5800

networks:
  hadoop-net:
    
volumes:
  hadoop_namenode:
  hadoop_datanode: