version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - target: 9870
        published: 9870
        protocol: tcp
        mode: host
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    networks:
      - host
     
  
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://172.16.0.3:9000
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    
    networks:
      - host
   
    ports:
        - 9864:9864
      
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://172.16.0.3:9000
    env_file:
      - ./hadoop.env

networks:
  host:
    
volumes:
  hadoop_namenode1:
  hadoop_datanode2:


  