version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    # restart: always
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
      
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode2
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data   
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
      
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode3
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env


  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode4
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:

networks:
  hadoop-net: