version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 9093:9870
      - 9092:40208
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
  
      
      

    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    volumes:
      - hadoop_datanode:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "144.178.108.18:40209"
      CORE_CONF_fs_defaultFS: "hdfs://144.178.108.18:40208"
    env_file:
      - ./hadoop.env
     

  firefox:
    image: jlesage/firefox
    ports:
      - 9094:5800
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
