version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 9093:9870
      - 9092:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_namenode_secondary_http__address=0.0.0.0:9000
      - HDFS_CONF_dfs_namenode-rpc-bind-host=0.0.0.0:9000
      - HDFS_CONF_dfs_namenode_servicerpc-bind-host=0.0.0.0:9000


    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    volumes:
      - hadoop_datanode:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: "hdfs://namenode:40208"
    env_file:
      - ./hadoop.env
     

  firefox:
    image: jlesage/firefox
    ports:
      - 9094:5800
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
