version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode4:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
     

  firefox:
    image: jlesage/firefox
    ports:
      - 18080:5800
  
volumes:
  hadoop_namenode4:
  hadoop_datanode4:
