version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS="hdfs://namenode:9000"
      - CORE_CONF_hadoop_http_staticuser_user="root"
      - CORE_CONF_hadoop_proxyuser_hue_hosts="*"
      - CORE_CONF_hadoop_proxyuser_hue_groups="*"
      - CORE_CONF_io_compression_codecs="org.apache.hadoop.io.compress.SnappyCodec"

      - HDFS_CONF_dfs_webhdfs_enabled="true"
      - HDFS_CONF_dfs_permissions_enabled="false"
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check="false"

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
      CORE_CONF_hadoop_proxyuser_hue_groups: "*"
      CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

      HDFS_CONF_dfs_webhdfs_enabled: true
      HDFS_CONF_dfs_permissions_enabled: false
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: false
      
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode2
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data   
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
      CORE_CONF_hadoop_proxyuser_hue_groups: "*"
      CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

      HDFS_CONF_dfs_webhdfs_enabled: true
      HDFS_CONF_dfs_permissions_enabled: false
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: false
      
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode3
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
      CORE_CONF_hadoop_proxyuser_hue_groups: "*"
      CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

      HDFS_CONF_dfs_webhdfs_enabled: true
      HDFS_CONF_dfs_permissions_enabled: false
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: false


  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode4
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    restart: always
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
      CORE_CONF_hadoop_proxyuser_hue_groups: "*"
      CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

      HDFS_CONF_dfs_webhdfs_enabled: true
      HDFS_CONF_dfs_permissions_enabled: false
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: false

  
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:

networks:
  hadoop-net: