version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
volumes:
  hadoop_namenode:

networks:
  hadoop-net: