version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      hostnet: {}
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenodedns:9000
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode1
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    networks:
      hostnet: {}
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.hadoop==1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data    
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenodedns:9000
      
    env_file:
      - ./hadoop.env  
    
volumes:
  hadoop_namenode:
  hadoop_datanode1:


networks:
  hostnet:
    external: true
    name: host